name: Undercontroll infra workflow

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy infrastructure"
        required: true
        default: false
        type: boolean
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: infra-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      destroy: ${{ steps.set.outputs.destroy }}
      apply: ${{ steps.set.outputs.apply }}
    steps:
      - name: Set destroy variable
        id: set
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "destroy=${{ inputs.destroy }}" >> "$GITHUB_OUTPUT"
          else
            echo "destroy=false" >> "$GITHUB_OUTPUT"
          fi

          if [ "${{ github.event_name }}" = "pull_request" ] || [ "${{ inputs.destroy }}" = "true" ]; then
            echo "apply=false" >> "$GITHUB_OUTPUT"
          else
            echo "apply=true" >> "$GITHUB_OUTPUT"
          fi

  terraform:
    needs: prepare
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      destroy: ${{ fromJSON(needs.prepare.outputs.destroy) }}
      apply: ${{ fromJSON(needs.prepare.outputs.apply) }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      DEPLOY_PUBLIC_KEY: ${{ secrets.DEPLOY_PUBLIC_KEY }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  observability:
    needs: terraform
    uses: ./.github/workflows/observability.yml
    with:
      albIp: ${{ needs.terraform.outputs.alb_public_ip }}
