name: Undercontroll main workflow

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      destroy: ${{ steps.set.outputs.destroy }}
    steps:
      - name: Set destroy variable
        id: set
        # Mudar para false caso queira subir a infra
        run: echo "destroy=false" >> $GITHUB_OUTPUT

  terraform:
    needs: prepare
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-region: "us-east-1"
      destroy: ${{ needs.prepare.outputs.destroy }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_STATE_S3_BUCKET: ${{ secrets.AWS_STATE_S3_BUCKET }}
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}
