name: "Terraform infra workflow"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      destroy:
        required: true
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      RABBITMQ_USER:
        required: true
      RABBITMQ_PASSWORD:
        required: true
      DEPLOY_PUBLIC_KEY:
        required: true
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      JWT_SECRET:
        required: true
      MAIL_HOST:
        required: true
      MAIL_PORT:
        required: true
      MAIL_USERNAME:
        required: true
      MAIL_PASSWORD:
        required: true
      GH_PAT:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      rabbitmq_ip: ${{ steps.outputs.outputs.rabbitmq_ip }}
      frontend_public_ip: ${{ steps.outputs.outputs.frontend_public_ip }}
      backend_private_ip: ${{ steps.outputs.outputs.backend_private_ip }}
      database_private_ip: ${{ steps.outputs.outputs.database_private_ip }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform init
        run: cd infra && terraform init

      - name: Terraform validate
        run: cd infra && terraform validate

      - name: Terraform destroy
        if: ${{ inputs.destroy == true }}
        id: terraform-destroy
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy \
            -var-file="./environments/${{ inputs.environment }}/terraform.tfvars" \
            -var="rabbitmq_user=${{ secrets.RABBITMQ_USER }}" \
            -var="rabbitmq_password=${{ secrets.RABBITMQ_PASSWORD }}" \
            -var="deploy_public_key=${{ secrets.DEPLOY_PUBLIC_KEY }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -auto-approve

      - name: Terraform plan
        if: ${{ !inputs.destroy }}
        id: terraform-plan
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan \
            -var-file="./environments/${{ inputs.environment }}/terraform.tfvars" \
            -var="rabbitmq_user=${{ secrets.RABBITMQ_USER }}" \
            -var="rabbitmq_password=${{ secrets.RABBITMQ_PASSWORD }}" \
            -var="deploy_public_key=${{ secrets.DEPLOY_PUBLIC_KEY }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -out="${{ inputs.environment }}.plan"

      - name: Terraform apply
        if: ${{ !inputs.destroy }}
        id: terraform-apply
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"

      - name: Get Terraform Outputs
        id: outputs
        if: ${{ !inputs.destroy }}
        run: |
          cd infra
          echo "rabbitmq_ip=$(terraform output -raw rabbitmq_private_ip)" >> $GITHUB_OUTPUT
          echo "frontend_public_ip=$(terraform output -raw frontend_public_ip)" >> $GITHUB_OUTPUT
          echo "backend_private_ip=$(terraform output -raw backend_private_ip)" >> $GITHUB_OUTPUT
          echo "database_private_ip=$(terraform output -raw database_private_ip)" >> $GITHUB_OUTPUT

      - name: Sync secrets to repositories
        if: ${{ !inputs.destroy }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          FRONTEND_PUBLIC_IP: ${{ steps.outputs.outputs.frontend_public_ip }}
          BACKEND_PRIVATE_IP: ${{ steps.outputs.outputs.backend_private_ip }}
          RABBITMQ_IP: ${{ steps.outputs.outputs.rabbitmq_ip }}
          DATABASE_PRIVATE_IP: ${{ steps.outputs.outputs.database_private_ip }}
          RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          gh secret set EC2_HOST \
            --repo undercontroll-inc/frontend \
            --body "${FRONTEND_PUBLIC_IP}"

          gh secret set VITE_API_URL \
            --repo undercontroll-inc/frontend \
            --body "/v1/api"

          gh secret set BACKEND_PRIVATE_IP \
            --repo undercontroll-inc/frontend \
            --body "${BACKEND_PRIVATE_IP}"

          for repo in main-service notification-api; do
            gh secret set RABBITMQ_HOST \
              --repo "undercontroll-inc/${repo}" \
              --body "${RABBITMQ_IP}"

            gh secret set RABBITMQ_USERNAME \
              --repo "undercontroll-inc/${repo}" \
              --body "${RABBITMQ_USERNAME}"

            gh secret set RABBITMQ_PASSWORD \
              --repo "undercontroll-inc/${repo}" \
              --body "${RABBITMQ_PASSWORD}"

            gh secret set DB_HOST \
              --repo "undercontroll-inc/${repo}" \
              --body "${DATABASE_PRIVATE_IP}"

            gh secret set DB_USERNAME \
              --repo "undercontroll-inc/${repo}" \
              --body "${DB_USERNAME}"

            gh secret set DB_PASSWORD \
              --repo "undercontroll-inc/${repo}" \
              --body "${DB_PASSWORD}"

            gh secret set JWT_SECRET \
              --repo "undercontroll-inc/${repo}" \
              --body "${JWT_SECRET}"

            gh secret set BACKEND_EC2_HOST \
              --repo "undercontroll-inc/${repo}" \
              --body "${BACKEND_PRIVATE_IP}"

            gh secret set BASTION_HOST \
              --repo "undercontroll-inc/${repo}" \
              --body "${FRONTEND_PUBLIC_IP}"

            gh secret set MAIL_HOST \
              --repo "undercontroll-inc/${repo}" \
              --body "${MAIL_HOST}"

            gh secret set MAIL_PORT \
              --repo "undercontroll-inc/${repo}" \
              --body "${MAIL_PORT}"

            gh secret set MAIL_USERNAME \
              --repo "undercontroll-inc/${repo}" \
              --body "${MAIL_USERNAME}"

            gh secret set MAIL_PASSWORD \
              --repo "undercontroll-inc/${repo}" \
              --body "${MAIL_PASSWORD}"
          done
